@startuml
annotation java.lang.Override
class MazeGUI.JFrame
class MazeGUI.JPanel
class MazeGUI.MazeFrame
class MazeGUI.MazePanel
class MazeGUI.SettingsFrame
class MazeLogic.FileNotCorrectException
class MazeLogic.Maze
class MazeLogic.Properties
class com.formdev.flatlaf.FlatDarkLaf
class java.io.File
class java.io.FileWriter
class java.io.IOException
class javax.swing.filechooser.FileNameExtensionFilter
MazeGUI.MazeFrame ..> java.lang.Override
MazeGUI.MazeFrame --|> MazeGUI.JFrame
MazeGUI.MazeFrame ..> MazeLogic.FileNotCorrectException
MazeGUI.MazeFrame ..> MazeLogic.Properties
MazeGUI.MazeFrame ..> com.formdev.flatlaf.FlatDarkLaf
MazeGUI.MazeFrame ..> java.io.File
MazeGUI.MazeFrame ..> java.io.FileWriter
MazeGUI.MazeFrame ..> java.io.IOException
MazeGUI.MazeFrame ..> javax.swing.filechooser.FileNameExtensionFilter
MazeGUI.MazePanel ..> java.lang.Override
MazeGUI.MazePanel --|> MazeGUI.JPanel
MazeGUI.MazePanel ..> MazeLogic.Maze
MazeGUI.MazePanel ..> MazeLogic.Properties
MazeGUI.SettingsFrame --|> MazeGUI.JFrame
MazeGUI.SettingsFrame ..> MazeLogic.Properties
@enduml